use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

use crate::constants::{CONF_FILE_NAME, DEFAULT_RPC_PORT, SESSION_FILE_NAME};

/// Ensure the aria2.conf file exists in the app data directory.
/// If it already exists, return its path (preserving user edits).
/// If not (first run), generate a default configuration file.
pub fn ensure_conf_file(app_data_dir: &Path) -> Result<PathBuf, String> {
    fs::create_dir_all(app_data_dir)
        .map_err(|e| format!("Failed to create app data dir: {}", e))?;

    let conf_path = app_data_dir.join(CONF_FILE_NAME);

    if conf_path.exists() {
        return Ok(conf_path);
    }

    // Generate default aria2.conf
    let download_dir = normalize_path(&dirs_default_download());
    let session_path = normalize_path(&app_data_dir.join(SESSION_FILE_NAME).to_string_lossy());

    let content = format!(
        "\
# aria2 configuration - generated by AriaNg App
# Edit this file to customize aria2 settings.
# Changes take effect on next application restart.

# RPC settings
enable-rpc=true
rpc-listen-port={port}
rpc-listen-all=false
rpc-allow-origin-all=true
# rpc-secret=

# Download settings
dir={download_dir}
max-concurrent-downloads=5
continue=true
max-connection-per-server=16
min-split-size=1M
split=16

# Session persistence
save-session={session}
input-file={session}
save-session-interval=30
auto-save-interval=30

# Security
check-certificate=true
",
        port = DEFAULT_RPC_PORT,
        download_dir = download_dir,
        session = session_path,
    );

    fs::write(&conf_path, content).map_err(|e| format!("Failed to write aria2.conf: {}", e))?;

    Ok(conf_path)
}

/// Read the preferred RPC port from aria2.conf.
/// Falls back to DEFAULT_RPC_PORT if the file is unreadable or the key is missing.
pub fn get_preferred_port(conf_path: &Path) -> u16 {
    read_conf_value(conf_path, "rpc-listen-port")
        .and_then(|v| v.parse::<u16>().ok())
        .unwrap_or(DEFAULT_RPC_PORT)
}

/// Read the RPC secret from aria2.conf.
/// Returns an empty string if absent or commented out.
pub fn get_rpc_secret(conf_path: &Path) -> String {
    read_conf_value(conf_path, "rpc-secret").unwrap_or_default()
}

/// Ensure the aria2 session file exists (aria2 requires it for --input-file).
pub fn ensure_session_file(app_data_dir: &Path) -> Result<PathBuf, String> {
    let session_path = app_data_dir.join(SESSION_FILE_NAME);
    if !session_path.exists() {
        fs::write(&session_path, "")
            .map_err(|e| format!("Failed to create session file: {}", e))?;
    }
    Ok(session_path)
}

/// Read a single key=value from an aria2 conf file.
/// Skips comments (lines starting with #) and blank lines.
fn read_conf_value(conf_path: &Path, key: &str) -> Option<String> {
    let content = fs::read_to_string(conf_path).ok()?;
    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        if let Some((k, v)) = trimmed.split_once('=') {
            if k.trim() == key {
                return Some(v.trim().to_string());
            }
        }
    }
    None
}

/// Keys managed internally by the app that should NOT be overwritten by runtime options.
/// These are set by the app (session paths, RPC listen settings) or are
/// read-only in aria2's getGlobalOption response.
const INTERNAL_KEYS: &[&str] = &[
    "enable-rpc",
    "rpc-listen-port",
    "rpc-listen-all",
    "rpc-allow-origin-all",
    "rpc-secret",
    "save-session",
    "input-file",
];

/// User-configurable keys that are meaningful to persist from runtime options.
/// aria2.getGlobalOption returns many internal/read-only options; only persist
/// these well-known user-configurable options to keep the conf file clean.
const USER_CONFIGURABLE_KEYS: &[&str] = &[
    "dir",
    "max-concurrent-downloads",
    "max-connection-per-server",
    "min-split-size",
    "split",
    "continue",
    "max-overall-download-limit",
    "max-overall-upload-limit",
    "max-download-limit",
    "max-upload-limit",
    "lowest-speed-limit",
    "max-tries",
    "retry-wait",
    "timeout",
    "connect-timeout",
    "bt-max-peers",
    "seed-ratio",
    "seed-time",
    "check-certificate",
    "user-agent",
    "proxy-method",
    "all-proxy",
    "all-proxy-user",
    "all-proxy-passwd",
    "http-proxy",
    "https-proxy",
    "no-proxy",
    "save-session-interval",
    "auto-save-interval",
];

/// Sync the aria2.conf file with runtime options fetched via aria2.getGlobalOption.
/// Updates existing keys that have changed values, and appends new user-configurable
/// keys that appear in runtime but not yet in the conf file.
/// Returns Ok(true) if the file was modified, Ok(false) if no changes were needed.
pub fn sync_conf_with_runtime(
    conf_path: &Path,
    runtime_options: &HashMap<String, String>,
) -> Result<bool, String> {
    let content =
        fs::read_to_string(conf_path).map_err(|e| format!("Failed to read aria2.conf: {}", e))?;

    let mut lines: Vec<String> = content.lines().map(|l| l.to_string()).collect();
    let mut modified = false;

    // Track which runtime keys we've already handled (matched to existing conf lines)
    let mut handled_keys: std::collections::HashSet<String> = std::collections::HashSet::new();

    // Pass 1: Update existing conf lines if the runtime value differs
    for line in lines.iter_mut() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        if let Some((key, old_value)) = trimmed.split_once('=') {
            let key = key.trim();
            let old_value = old_value.trim();

            // Skip internal/app-managed keys
            if INTERNAL_KEYS.contains(&key) {
                handled_keys.insert(key.to_string());
                continue;
            }

            if let Some(new_value) = runtime_options.get(key) {
                handled_keys.insert(key.to_string());
                if old_value != new_value {
                    *line = format!("{}={}", key, new_value);
                    modified = true;
                }
            }
        }
    }

    // Pass 2: Append new user-configurable keys from runtime that aren't in conf yet
    for key in USER_CONFIGURABLE_KEYS {
        if handled_keys.contains(*key) || INTERNAL_KEYS.contains(key) {
            continue;
        }
        if let Some(value) = runtime_options.get(*key) {
            if !value.is_empty() {
                lines.push(format!("{}={}", key, value));
                modified = true;
            }
        }
    }

    if modified {
        let new_content = lines.join("\n") + "\n";
        fs::write(conf_path, new_content)
            .map_err(|e| format!("Failed to write aria2.conf: {}", e))?;
    }

    Ok(modified)
}

/// Normalize path separators to forward slashes for aria2 compatibility on Windows.
fn normalize_path(path: &str) -> String {
    path.replace('\\', "/")
}

/// Get the default download directory for the current platform.
fn dirs_default_download() -> String {
    if let Some(home) = home_dir() {
        let downloads = home.join("Downloads");
        if downloads.exists() {
            return downloads.to_string_lossy().to_string();
        }
        return home.to_string_lossy().to_string();
    }
    ".".to_string()
}

/// Cross-platform home directory detection.
fn home_dir() -> Option<PathBuf> {
    #[cfg(target_os = "windows")]
    {
        std::env::var("USERPROFILE").ok().map(PathBuf::from)
    }
    #[cfg(not(target_os = "windows"))]
    {
        std::env::var("HOME").ok().map(PathBuf::from)
    }
}
